function mostrar()
{
	var edad;

	edad=document.getElementById('edad').value;

	if (edad==15)
	{
		alert("Niña bonita");
	}					  



}//FIN DE LA FUNCIÓN

/* EVALUA TRUE OR FALSE SI ES TRUE EJECUTA EL PRIMER PARENTESIS, SINO CONTINUA HASTA EL FINAL DE LA LLAVE Y SIGUE LEYENDO
OPERADORES DE COMPARACION: SON OPERADORES BINARIOS, NECESITAN 2 OPERARIOS UNO A LA IZQ Y LA DERECHA...
IGUALDAD ==, != DISTINTO, EL SIGNO DE ADMIRACION NIEGA LO QUE SIGUE..., !TRUE=FALSE, CUALQUIER COSA ADELANTE DEL SIGNO DE ADMIRACION SE NIEGA

OJO CONCEPTO NUEVO IGUALDAD ESTRICTA...
IGUALDAD ESTRICTA === OJOOO LA DIFERENCIA ES Q ESTA COMPARA LOS TIPOS DE VALORES, LOS TIPOS DE VARIABLES, 
TRUE=="TRUE" CON EL IGUAL IGUAL COMPARA LOS VALORES, CON LA IGUALDAD ESTRICTA TE COMPARA EL TIPO DE DATO, NO SIGUE COMPARANDO SINO
SON DEL MISMO TIPO...OJJJOOOO, PRIMERO IGUALA EL TIPO DE VALOR, SI ES IGUAL ES TRUE...Y DSP SIGUE, POR AHORA SE USA LA SIMPLE PARA
EVITAR ERRORES..TRUE==="TRUE" =FALSE
BINARIO ES POR QUE LOS COMPARADORES NECESITAN 2 VALORES PARA COMPARAR, NO POR QUE SON 2 ELEMENTOS EL ==...SUP IMP

OPERADORES LOGICOS:
 && (y)   // (O)   SUPER IMP!! ES Y O DE MATEMATICA, LAS TABLITAS DE VERDAD!!

NOS SIRVEN CUANDO QUEREMOS EVALUAR MAS DE UNA CONDICION, EJ EDAD==8 // SEXO==MASC , ACA VA A DECIR TRUE CUANDO SE 
CUMPLAN AMBAS FUNCIONES...

ELSE
NO LLEVA CONDICION, SE EJECUTA SINO SE EJECUTA EL IF, POR CADA IF VA UN SOLO ELSE, 
SIEMPRE SE PONE LA LLAVE AUNQUE SINO SE PONE, TOMA LA PRIMERA LINEA DE ABAJO COMO CONDICION. 

*/